=== dasger3/async_Smak/src/main/java/Voronin/MicroService/Lab1/XML/gun.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="guns">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="gun" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>

                            <xsd:element name="model" type="xsd:string"/>

                            <xsd:element name="handy">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:enumeration value="ONE_HANDED"/>
                                        <xsd:enumeration value="TWO_HANDED"/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>

                            <xsd:element  name="origin">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:pattern value="[A-Za-z]{2,}"/>

                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>


                            <xsd:element name="material">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:maxLength value="10"/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>

                            <xsd:element name="TTC">
                                <xsd:complexType>
                                    <xsd:sequence>

                                        <xsd:element name="range">
                                            <xsd:simpleType>
                                                <xsd:restriction base="xsd:string">
                                                    <xsd:enumeration value="CLOSE_0_500"/>
                                                    <xsd:enumeration value="MIDDLE_500_1000"/>
                                                    <xsd:enumeration value="LONG_MORE_1000M"/>
                                                </xsd:restriction>
                                            </xsd:simpleType>
                                        </xsd:element>

                                        <xsd:element name="sightingRange">
                                            <xsd:simpleType>
                                                <xsd:restriction base="xsd:double">
                                                    <xsd:pattern value="\d+\.\d{2}"/>
                                                </xsd:restriction>
                                            </xsd:simpleType>
                                        </xsd:element>

                                        <xsd:element name="hasClip" type="xsd:boolean"/>

                                        <xsd:element name="hasOptics" type="xsd:boolean"/>

                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>

                        </xsd:sequence>

                        <xsd:attribute name="id" type="xsd:integer"/>

                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>

        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== dasger3/async_Smak/src/main/java/Voronin/MicroService/Lab1/XML/gun.xml
<?xml version="1.0" encoding="UTF-8" ?>

<guns xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="gun.xsd">
  <!--1 or more repetitions:-->
  <gun id="1">
    <model>First model</model>
    <handy>ONE_HANDED</handy>
    <origin>Germany</origin>
    <material>Iron</material>
    <TTC>
      <range>MIDDLE_500_1000</range>
      <sightingRange>100.00</sightingRange>
      <hasClip>true</hasClip>
      <hasOptics>true</hasOptics>
    </TTC>
  </gun>

  <gun id="2">
    <model>Second model</model>
    <handy>TWO_HANDED</handy>
    <origin>France</origin>
    <material>Iron</material>
    <TTC>
      <range>CLOSE_0_500</range>
      <sightingRange>50.00</sightingRange>
      <hasClip>true</hasClip>
      <hasOptics>false</hasOptics>
    </TTC>
  </gun>

  <gun id="3">
    <model>Third model</model>
    <handy>ONE_HANDED</handy>
    <origin>USA</origin>
    <material>Iron</material>
    <TTC>
      <range>MIDDLE_500_1000</range>
      <sightingRange>550.50</sightingRange>
      <hasClip>false</hasClip>
      <hasOptics>true</hasOptics>
    </TTC>
  </gun>
</guns>
