=== dasger3/async_Smak/src/main/java/Galushko/MicroService/Lab1/XML/knife.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="knives">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="knife" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>

                            <xsd:element name="type" type="xsd:string"/>

                            <xsd:element name="handy">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:enumeration value="ONE_HANDED"/>
                                        <xsd:enumeration value="TWO_HANDED"/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>

                            <xsd:element  name="origin">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:pattern value="[A-Za-z]{2,}"/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>

                            <xsd:element name="value" type="xsd:boolean"/>

                            <xsd:element name="Visual">
                                <xsd:complexType>
                                    <xsd:sequence>

                                        <xsd:element name="lengthOfKnife">
                                            <xsd:simpleType>
                                                <xsd:restriction base="xsd:double">
                                                    <xsd:pattern value="\d+\.\d{2}"/>
                                                    <xsd:minInclusive value="10"/>
                                                    <xsd:maxInclusive value="100"/>
                                                </xsd:restriction>
                                            </xsd:simpleType>
                                        </xsd:element>

                                        <xsd:element name="widthOfKnife">
                                            <xsd:simpleType>
                                                <xsd:restriction base="xsd:double">
                                                    <xsd:pattern value="\d+\.\d{2}"/>
                                                    <xsd:minInclusive value="10"/>
                                                    <xsd:maxInclusive value="100"/>
                                                </xsd:restriction>
                                            </xsd:simpleType>
                                        </xsd:element>

                                        <xsd:element name="material" type="xsd:string"/>

                                        <xsd:element name="handle" type="xsd:string"/>

                                        <xsd:element name="bloodstream" type="xsd:boolean"/>

                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>

                        </xsd:sequence>

                        <xsd:attribute name="id" type="xsd:integer"/>

                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>

        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== dasger3/async_Smak/src/main/java/Galushko/MicroService/Lab1/XML/knife.xml
<?xml version="1.0" encoding="UTF-8" ?>

<knives xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="knife.xsd">
  <!--1 or more repetitions:-->
  <knife id="1">
    <type>Knife</type>
    <handy>TWO_HANDED</handy>
    <origin>USA</origin>
    <value>true</value>
    <Visual>
      <lengthOfKnife>30.00</lengthOfKnife>
      <widthOfKnife>40.03</widthOfKnife>
      <material>Iron</material>
      <handle>Wood, oak</handle>
      <bloodstream>true</bloodstream>
    </Visual>
  </knife>

  <knife id="2">
    <type>Dagger</type>
    <handy>ONE_HANDED</handy>
    <origin>Germany</origin>
    <value>false</value>
    <Visual>
      <lengthOfKnife>10.00</lengthOfKnife>
      <widthOfKnife>10.22</widthOfKnife>
      <material>Plastic</material>
      <handle>Wood, ash</handle>
      <bloodstream>false</bloodstream>
    </Visual>
  </knife>

  <knife id="3">
    <type>Saber</type>
    <handy>ONE_HANDED</handy>
    <origin>England</origin>
    <value>false</value>
    <Visual>
      <lengthOfKnife>90.00</lengthOfKnife>
      <widthOfKnife>33.33</widthOfKnife>
      <material>Iron</material>
      <handle>Plastic</handle>
      <bloodstream>true</bloodstream>
    </Visual>
  </knife>

</knives>
