=== dasger3/async_Smak/src/main/java/Volos/MicroService/Lab1/XML/computer.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="computers">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="computer" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>

                            <xsd:element name="name" type="xsd:string"/>

                            <xsd:element  name="origin">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:pattern value="[A-Za-z]{2,}"/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>

                            <xsd:element name="price">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:double">
                                        <xsd:pattern value="\d+\.\d{2}"/>
                                        <xsd:minInclusive value="0"/>
                                        <xsd:maxInclusive value="100"/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>

                            <xsd:element name="critical" type="xsd:boolean"/>

                            <xsd:element name="Type">
                                <xsd:complexType>
                                    <xsd:sequence>

                                        <xsd:element name="isPeripheral" type="xsd:boolean"/>

                                        <xsd:element name="energyConsumption">
                                            <xsd:simpleType>
                                                <xsd:restriction base="xsd:double">
                                                    <xsd:pattern value="\d+\.\d{2}"/>
                                                </xsd:restriction>
                                            </xsd:simpleType>
                                        </xsd:element>

                                        <xsd:element name="hasCooler" type="xsd:boolean"/>

                                        <xsd:element name="Ports">
                                            <xsd:simpleType>
                                                <xsd:restriction base="xsd:string">
                                                    <xsd:enumeration value="COM"/>
                                                    <xsd:enumeration value="USB"/>
                                                    <xsd:enumeration value="LPT"/>
                                                </xsd:restriction>
                                            </xsd:simpleType>
                                        </xsd:element>

                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>

                        </xsd:sequence>

                        <xsd:attribute name="id" type="xsd:integer"/>

                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>

        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== dasger3/async_Smak/src/main/java/Volos/MicroService/Lab1/XML/computer.xml
<?xml version="1.0" encoding="UTF-8" ?>

<computers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="computer.xsd">
  <!--1 or more repetitions:-->
  <computer id="1">
    <name>First computer</name>
    <origin>USA</origin>
    <price>99.44</price>
    <critical>false</critical>
    <Type>
      <isPeripheral>true</isPeripheral>
      <energyConsumption>132.00</energyConsumption>
      <hasCooler>true</hasCooler>
      <Ports>COM</Ports>
    </Type>
  </computer>

  <computer id="2">
    <name>Second computer</name>
    <origin>Germany</origin>
    <price>42.99</price>
    <critical>false</critical>
    <Type>
      <isPeripheral>true</isPeripheral>
      <energyConsumption>111.11</energyConsumption>
      <hasCooler>true</hasCooler>
      <Ports>LPT</Ports>
    </Type>
  </computer>

  <computer id="3">
    <name>Third computer</name>
    <origin>Ukraine</origin>
    <price>100.00</price>
    <critical>true</critical>
    <Type>
      <isPeripheral>false</isPeripheral>
      <energyConsumption>140.32</energyConsumption>
      <hasCooler>true</hasCooler>
      <Ports>USB</Ports>
    </Type>
  </computer>

</computers>
